# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField(max_length=4)),
                ('bookname', models.CharField(max_length=75)),
                ('bookpublisher', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'library',
            },
        ),
    ]
